FROM tomcat:9-jre8
LABEL maintainer="mohan <23mh1a4435@gmail.com>"

EXPOSE 8080

# Remove default Tomcat applications (optional but recommended)
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file generated by Maven
COPY target/maven-web-app.war /usr/local/tomcat/webapps/maven-web-app.war
